apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sample-app
  namespace: sample-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/instance: sample-app
